### ISSUE TITLE
Enhancement: missing pattern name should be okay

### ISSUE THREAD

**Issue by faxm0dem** [ihrwein/actiondb#46]
this fails: `genunix: [ID %{GREEDY:} %{GREEDY} core_log: ...`

it should be allowed to set no key in `%{type:key}`

**Comment by faxm0dem** [comment]
same goes for tags:
```
Unexpected tags found either in the parse result or among the expected ones: expected: None got=Some(["postfix", "pickup"])
```

**Comment by ihrwein** [comment]
I've created an issue for the tags half #50

**Comment by ihrwein** [comment]
I think the syntax will be just: `%{GREEDY}`.
